name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create users.json from GitHub secrets
        run: |
          mkdir -p data
          echo '{
            "standard_user": {
              "username": "${{ secrets.STANDARD_USER }}",
              "password": "${{ secrets.SECRET_SAUCE }}"
            }
          }' > data/users.json

      - name: Run Playwright tests
        run: npx playwright test

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git fetch
          git worktree add gh-pages

          cp -r playwright-report/* gh-pages/
          touch gh-pages/.nojekyll

          cd gh-pages
          git add .
          git commit -m "deploy: playwright report"
          git push --force origin HEAD:gh-pages
